package com.minhle.test;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data 
@AllArgsConstructor 
@NoArgsConstructor 
public class MusicCompositeKey implements Serializable {
 
   @DynamoDBHashKey 
   @DynamoDBAutoGeneratedKey 
   private String artist; 
   @DynamoDBRangeKey 
   private String songTitle; 
}