package com.minhle.model.user;  
import java.util.Collection;
import java.util.Collections;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.UniqueElements;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.minhle.model.role.UserRole;
 

@DynamoDBTable(tableName = "KitchenProviderUser") 
@Component
public class KitchenProviderUser implements UserDetails {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	private String id;
    
    @NotNull
    @Size(max = 50)
    @UniqueElements
    @DynamoDBAttribute(attributeName = "Service_Provider_Name")
    private String name;
    
    @Email
    @NotNull
    @Size(max = 50)
    @UniqueElements
    @DynamoDBAttribute(attributeName = "Email")
	private String email;
    
    @NotNull
    @Size(min = 10,max = 50)
    @DynamoDBAttribute(attributeName = "Password")
	private String password;
    
     
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return "\n"+ email + " " + password ;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public KitchenProviderUser() {
		super();
	}
	public KitchenProviderUser(String id, String email, String password) {
		super();
		this.id = id;
		this.email = email;
		this.password = password;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
 
	public void setPassword(String password) {
		this.password = password;
	}
 
 
	public void setName(String name) {
		this.name = name;
	}
	@Override
	public Collection<? extends GrantedAuthority> getAuthorities() {
		// TODO Auto-generated method stub
		final SimpleGrantedAuthority simpleGrantedAuthority = new SimpleGrantedAuthority(UserRole.PROVIDER.name());
		return Collections.singletonList(simpleGrantedAuthority);
	}
	@Override
	public String getUsername() {
		// TODO Auto-generated method stub
		return this.name;
	}
	@Override
	public boolean isAccountNonExpired() {
		// TODO Auto-generated method stub
		return true;
	}
	@Override
	public boolean isAccountNonLocked() {
		// TODO Auto-generated method stub
		return true;
	}
	@Override
	public boolean isCredentialsNonExpired() {
		// TODO Auto-generated method stub
		return true;
	}
	@Override
	public boolean isEnabled() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public String getPassword() {
		// TODO Auto-generated method stub
		return password;
	}
 

}
