package com.minhle.model.user;

import java.util.Collection;
import java.util.Collections;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.UniqueElements;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.minhle.model.role.UserRole;
 

@DynamoDBTable(tableName = "KitchenProviderUser") 
@Component
public class KitchenProviderUserPrincipal implements UserDetails {

     private KitchenProviderUser user;
     public KitchenProviderUserPrincipal(KitchenProviderUser user) {
		// TODO Auto-generated constructor stub
    	 this.user = user;
	}
	 
	@Override
	public Collection<? extends GrantedAuthority> getAuthorities() {
		// TODO Auto-generated method stub
		final SimpleGrantedAuthority simpleGrantedAuthority = new SimpleGrantedAuthority(UserRole.PROVIDER.name());
		return Collections.singletonList(simpleGrantedAuthority);
	}
	@Override
	public String getUsername() {
		// TODO Auto-generated method stub
		return this.user.getName();
	}
	@Override
	public boolean isAccountNonExpired() {
		// TODO Auto-generated method stub
		return true;
	}
	@Override
	public boolean isAccountNonLocked() {
		// TODO Auto-generated method stub
		return true;
	}
	@Override
	public boolean isCredentialsNonExpired() {
		// TODO Auto-generated method stub
		return true;
	}
	@Override
	public boolean isEnabled() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public String getPassword() {
		// TODO Auto-generated method stub
		return this.user.getPassword();
	}

}
