package com.minhle.model.kitchen; 
import java.util.List; 
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable; 
@DynamoDBTable(tableName = "Cart")
public class Cart {
private String cartid;
	
	@DynamoDBAttribute
	private  String userCartname;
	
    @DynamoDBAttribute
	List<String> Item;
   
    @DynamoDBAttribute
    Double price;
  
	public Cart(String userCartname, List<String> item) {
		super();
		this.userCartname = userCartname;
		Item = item;
	}

	public Cart() {
		// TODO Auto-generated constructor stub
	}

	@DynamoDBHashKey(attributeName="cartid")
    @DynamoDBAutoGeneratedKey
    public String getCartid() {
		return cartid;
	}

	public void setCartid(String cartid) {
		this.cartid = cartid;
	}
	
		
	public String getUserCartname() {
		return userCartname;
	}
	
	public void setUserCartname(String userCartname) {
		this.userCartname = userCartname;
	}
	
	public List<String> getItems() {
		return Item;
	}
	
	public void setItems(List<String> item) {
		Item = item;
	}


	
}
