package com.minhle.model.kitchen;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

 

@DynamoDBTable(tableName = "Cart")
public class Cart {
private String cartid;
	
	@DynamoDBAttribute
	private  String userCartname;
	
   @DynamoDBAttribute
	List<String> Item;
   
   @DynamoDBHashKey(attributeName="cartid")
   @DynamoDBAutoGeneratedKey
   public String getCartid() {
		return cartid;
	}

	public void setCartid(String cartid) {
		this.cartid = cartid;
	}
		
public String getUserCartname() {
	return userCartname;
}

public void setUserCartname(String userCartname) {
	this.userCartname = userCartname;
}

public List<String> getItem() {
	return Item;
}

public void setItem(List<String> item) {
	Item = item;
}


	
}
