//package com.minhle.model.kitchen; 
//import java.util.List;
//
//import org.springframework.stereotype.Component;
//
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
//
//import lombok.Data;
//import lombok.RequiredArgsConstructor; 
//@DynamoDBTable(tableName = "Cart")
//@Component
//@Data
//@RequiredArgsConstructor
//public class Cart {
//
//	@DynamoDBHashKey(attributeName="cartid")
//    @DynamoDBAutoGeneratedKey
//     
//    final private String cartid;
//	
//	@DynamoDBAttribute
//	private  String userCartname;
//	
//    @DynamoDBAttribute
//	List<String> Item;
//   
//    @DynamoDBAttribute
//    Double price;
// 
// 
//
//
//	
//}
