package com.minhle.model.kitchen;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Kitchens")
public class Item { 
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "ItemId")
	private String id;
	@DynamoDBAttribute(attributeName = "Name")
	private String name;
	@DynamoDBAttribute(attributeName = "VegOption")
	private boolean vegOption;
	@DynamoDBAttribute(attributeName = "Price")
	private Double price;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isVegOption() {
		return vegOption;
	}

	public void setVegOption(boolean vegOption) {
		this.vegOption = vegOption;
	}

	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}  
}
