package com.minhle.model.kitchen;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "item")
public class Item {
	
	
	
	private String itemid;
	 @DynamoDBAttribute(attributeName="itemname")
	 private String name;
	 @DynamoDBAttribute
	 private boolean vegOption;
	 @DynamoDBAttribute
	 private Double price;
	 @DynamoDBHashKey(attributeName="itemid")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return itemid;
	}

	public void setId(String id) {
		this.itemid = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isVegOption() {
		return vegOption;
	}

	public void setVegOption(boolean vegOption) {
		this.vegOption = vegOption;
	}

	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}
	 
	 
	 
	 
	 

}
