package com.minhle.model.kitchen;  
import java.util.Set;

import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
 

@DynamoDBTable(tableName = "Kitchen")
@Component
public class Kitchen {
	@DynamoDBHashKey(attributeName = "kitchenid")
    @DynamoDBAutoGeneratedKey
	private String kitchenid;
	@DynamoDBAttribute
	private String providerEmail;
	@DynamoDBAttribute
	private String kitchenName;
	@DynamoDBAttribute
	private String date;
	@DynamoDBAttribute
	private String starttime;
	@DynamoDBAttribute
	private String endtime;
	@DynamoDBAttribute
	private String imageUrl;
	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = ItemConverter.class)
	private Set<Item> Menu ;

	public Set<Item> getMenu() {
		return Menu;
	}
	public void setMenu(Set<Item> menu) {
		Menu = menu;
	}
	public void addItem(Item item) {
		Menu.add(item);
	}
	public String getProviderEmail() {
		return providerEmail;
	}
	public void setProviderEmail(String providerName) {
		this.providerEmail = providerName;
	}

		public String getKitchenid() {
			return kitchenid;
		}
		public void setKitchenid(String kitchenid) {
			this.kitchenid = kitchenid;
		}

  public Kitchen() {
			super();
			kitchenName= "empty";
		}
public Kitchen(String providerEmail,String kitchenName, String date, String starttime, String endtime, String imageUrl, Set<Item> Menu
				 ) {
			super();
		 
			this.kitchenName = kitchenName;
			this.date = date;
			this.starttime = starttime;
			this.endtime = endtime;
			this.imageUrl = imageUrl; 
			this.Menu = Menu;
			 this.providerEmail = providerEmail;
		}
public String getKitchenName() {
		return kitchenName;
	}
	public void setKitchenName(String kitchenName) {
		this.kitchenName = kitchenName;
	}

	public String getDate() {
		return date;
	}
	public void setDate(String date) {
		this.date = date;
	}
	public String getStarttime() {
		return starttime;
	}
	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}
	public String getEndtime() {
		return endtime;
	}
	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}
	public String getImageUrl() {
		return imageUrl;
	}
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}
	@Override
	public String toString() {
		return "Kitchen [kitchenid=" + kitchenid + ", providerName=" + providerEmail + ", kitchenName=" + kitchenName
				+ ", date=" + date + ", starttime=" + starttime + ", endtime=" + endtime + ", imageUrl=" + imageUrl
				+ ", Menu=" + Menu + "]";
	}

	 
 
	
}

