package com.minhle.model.kitchen;  
import java.io.Serializable;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.springframework.stereotype.Component; 
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString; 
@DynamoDBTable(tableName = "Kitchen")
@Component
@ToString
@Data 
@AllArgsConstructor
@Builder
public class Kitchen implements Serializable{
	@DynamoDBHashKey(attributeName = "kitchenid")
	@DynamoDBAutoGeneratedKey
	private String kitchenid;
	@DynamoDBAttribute
	private String providerEmail;
	@DynamoDBAttribute
	private String kitchenName;
	@DynamoDBAttribute
	private String date;
	@DynamoDBAttribute
	private String starttime;
	@DynamoDBAttribute
	private String endtime;
	@DynamoDBAttribute
	private String imageUrl;
	@DynamoDBAttribute (attributeName = "menu") 
	private HashSet<String> menu ;
	 public Kitchen() { 
			kitchenName= "empty";
	}
	public Kitchen( String providerEmail, String kitchenName, String date, String starttime,
			String endtime, String imageUrl, HashSet<String> menu, String temporaryOrder) {
		super(); 
		this.providerEmail = providerEmail;
		this.kitchenName = kitchenName;
		this.date = date;
		this.starttime = starttime;
		this.endtime = endtime;
		this.imageUrl = imageUrl;
		this.menu = menu;
		 
	}
 
    
	
}

