package com.minhle.model.kitchen;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import java.util.Set;



import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
@Data
@AllArgsConstructor
@NoArgsConstructor

@DynamoDBTable(tableName = "Kitchen")
public class Kitchen {
	private String kitchenid;
	@DynamoDBAttribute
	private String kitchenName;
	@DynamoDBAttribute
	private String date;
	@DynamoDBAttribute
	private String starttime;
	@DynamoDBAttribute
	private String endtime;
	@DynamoDBAttribute
	private String imageUrl;
	@DynamoDBAttribute
	private Set<String> Menu ;
	
	@DynamoDBHashKey(attributeName = "Kitchenid")
	  @DynamoDBAutoGeneratedKey
		public String getKitchenid() {
			return kitchenid;
		}
		public void setKitchenid(String kitchenid) {
			this.kitchenid = kitchenid;
		}

  public String getKitchenName() {
		return kitchenName;
	}
	public void setKitchenName(String kitchenName) {
		this.kitchenName = kitchenName;
	}

	public String getDate() {
		return date;
	}
	public void setDate(String date) {
		this.date = date;
	}
	public String getStarttime() {
		return starttime;
	}
	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}
	public String getEndtime() {
		return endtime;
	}
	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}
	public String getImageUrl() {
		return imageUrl;
	}
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}
	public Set<String> getMenu() {
		return Menu;
	}
	public void setMenu(Set<String> menu) {
		Menu = menu;
	}
	@Override
	public String toString() {
		return " kitchenid=" + kitchenid + ", kitchenName=" + kitchenName + ", date=" + date + ", starttime="
				+ starttime + ", endtime=" + endtime + ", imageUrl=" + imageUrl + ", Menu=" + Menu;
	}
	
	
	



	
	
	

	
	
}

