package com.minhle.model.kitchen;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;

import org.joda.time.LocalDate;
import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;

import lombok.Data;
import lombok.RequiredArgsConstructor;


@Component
@Data 
public class Order implements Serializable{
	
 
  
	@DynamoDBHashKey(attributeName = "orderId")
	 @DynamoDBAutoGeneratedKey 
	 private String orderId;
	 @DynamoDBAttribute(attributeName = "listItem")
	 HashSet<String> Items;
	 
	 @DynamoDBAttribute(attributeName = "userEmail")
	 String userEmail;
	 @DynamoDBAttribute(attributeName = "total")
	 double total;
	 @Override
	 public String toString() {
		 return Items.toString()+"/"+ userEmail+ "/"+ total;
	 }
	public Order(HashSet<String> items, String userEmail, double total) {
		super();
		Items = items;
		this.userEmail = userEmail;
		this.total = total;
	}
	public Order() {
		super();
		Items = new HashSet<String>();
		 
		userEmail = "empty";
		total = 0;
	}
	 
	
	 
	 
}
